[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://osbackend.fly.dev"
  REACT_APP_WS_URL = "wss://osbackend.fly.dev"
  CI = "true"

[[redirects]]
  from = "/api/*"
  to = "https://osbackend.fly.dev/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"