[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  # Production Backend URL for Agent Command Center
  REACT_APP_API_URL = "https://agent-command-center-backend.onrender.com"
  REACT_APP_BACKEND_URL = "https://agent-command-center-backend.onrender.com"
  REACT_APP_WS_URL = "wss://agent-command-center-backend.onrender.com"
  
  # Supabase Configuration
  REACT_APP_SUPABASE_URL = "https://fiozmyoedptukpkzuhqm.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpb3pteW9lZHB0dWtwa3p1aHFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MTUxODcsImV4cCI6MjA2NTM5MTE4N30.XrzLFbtoOKcX0kU5K7MSPQKwTDNm6cFtefUGxSJzm-o"
  
  # Environment
  REACT_APP_ENVIRONMENT = "production"
  REACT_APP_FRONTEND_URL = "https://agent-command-center.netlify.app"
  
  # Build Configuration
  CI = "false"
  NODE_VERSION = "18"

# API Proxy Redirect
[[redirects]]
  from = "/api/*"
  to = "https://agent-command-center-backend.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# SPA Fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://agent-command-center-backend.onrender.com wss://agent-command-center-backend.onrender.com https://fiozmyoedptukpkzuhqm.supabase.co"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache Control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"