services:
  # Backend API Service
  - type: web
    name: agent-command-center-backend
    runtime: node
    repo: https://github.com/BoweryJG/agent-command-center
    branch: main
    rootDir: backend
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: SUPABASE_URL
        value: https://fiozmyoedptukpkzuhqm.supabase.co
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://agent-command-center.netlify.app,http://localhost:3000
      - key: AGENT_BACKEND_URL
        value: https://agentbackend-2932.onrender.com
      - key: REPCONNECT1_BACKEND_URL
        value: https://osbackend-zl1h.onrender.com
      - key: PEDRO_BACKEND_URL
        value: https://pedrobackend.onrender.com
      - key: AGENT_COMMAND_CENTER_URL
        value: https://agent-command-center.netlify.app
      - key: FRONTEND_URL
        value: https://agent-command-center.netlify.app
      - key: API_TIMEOUT
        value: 30000
      - key: MAX_RETRIES
        value: 3
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: LOG_LEVEL
        value: info
      - key: LOG_FORMAT
        value: json